#ingress.yaml
---
kind: Secret
apiVersion: v1
metadata:
  name: ngrok-oauth-secret
  namespace: test
type: Opaque
data:
  NGROK_CLIENT_SECRET: {}
---
kind: NgrokModuleSet
apiVersion: ingress.k8s.ngrok.com/v1alpha1
metadata:
  name: ngrok-module-set
  namespace: test
modules:
  oauth:
    microsoft:
      clientId: "68457528-4fed-4209-9eab-574a2ec5b90f"
      clientSecret:
        name: ngrok-oauth-secret
        key: CLIENT_SECRET
---
kind: Tunnel
apiVersion: ingress.k8s.ngrok.com/v1alpha1
metadata:
  name: ngrok-tunnel-set
  namespace: test
spec:
  forwardsTo: vote-app-service.test.svc.cluster.local:5001
  labels: 
    edge: "edghts_2pikBBwNZKGP62cKPD9NrQVzAEP"
    k8s.ngrok.com/namespace: test
    k8s.ngrok.com/service: vote-app-service
    k8s.ngrok.com/port: "80"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: test
  annotations:
    k8s.ngrok.com/modules: 
      ngrok-module-set
      ngrok-tunnel-set
spec:
  ingressClassName: ngrok
  rules:
    - host: bug-present-flamingo.ngrok-free.app
      http:
        paths:
          - path: /app1
            pathType: Prefix
            backend:
              service:
                name: vote-app-service
                port:
                  number: 5001
