---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: test
spec:
  selector:
    app: app-deploy-1
  ports:
  - name: app-port-1
    protocol: TCP
    port: 5001
    targetPort: 5001
  type: LoadBalancer
