# pipelines.yml

trigger:
  branches:
    include:
      - main
resources:
- repo: https://github.com/ntthuan0106/dacn

# Import variables from variables.yml
variables:
- template: '.azure-pipelines/variables.yml'
- group: 'NGROK'
- group: 'AZURE_CREDENTIALS'

stages:
- stage: BuildAndPush
  jobs:
  - job: BuildAndPushToACR
    displayName: Build and Push Docker Image to ACR
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        Dockerfile: $(dockerFilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageName)
        tags: |
          $(tag)
