# pipelines.yml

trigger:
  branches:
    include:
      - main
resources:
  repositories:
    - repository: dacn
      type: github
      name: 'ntthuan0106/dacn'
      endpoint: 'ntthuan0106'

# Import variables from variables.yml
variables:
- template: './variables.yml'
- group: 'NGROK'
- group: 'AZURE_CREDENTIALS'

stages:
- stage: BuildAndPush
  jobs:
  - job: BuildAndPushToACR
    displayName: Build and Push Docker Image to ACR
    pool: 
      name: 'Default'
      demand: Agent.Name -equals Agent1_DACN
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        Dockerfile: $(dockerFilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageName)
        tags: |
          $(imageTag)
- stage: Deploy
  jobs: 
  - job: Deploy
    displayName: Deploy To AKS
    pool:
      name: 'Default'
      demands: Agent.Name -equals Agent1_DACN
    steps:
    - bash: |
        pwd