trigger:
  - main  # or specify any branch you want to trigger this pipeline on

pool:
  vmImage: 'ubuntu-latest'  # Specify the virtual machine image to use

jobs:
- job: RunPwdCommand
  displayName: "Run pwd Command"
  steps:
    - script: pwd
      displayName: "Print Working Directory"
